name: 🚀 CI

on: 
  workflow_call: # Allow this workflow to be called from other workflows

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_CACHE: remote:rw

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci-lint-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Linting
        run: pnpm lint:check

  format:
    name: Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: 
      group: ci-format-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Formatting
        run: pnpm format:check

  typecheck:
    name: Typescript
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: 
      group: ci-typecheck-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Types
        run: pnpm typecheck


